"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from centralconfig.v1 import server_service_pb2 as _server_service_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ServerServiceStub:
    """ServerService provides server metadata and capability discovery.
    Always registered, no authentication required.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ServerServiceAsyncStub: ...
    GetServerInfo: _grpc.UnaryUnaryMultiCallable[_server_service_pb2.GetServerInfoRequest, _server_service_pb2.GetServerInfoResponse]
    """GetServerInfo returns the server's version, commit hash, and enabled features."""

@_typing.type_check_only
class ServerServiceAsyncStub(ServerServiceStub):
    """ServerService provides server metadata and capability discovery.
    Always registered, no authentication required.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    GetServerInfo: _aio.UnaryUnaryMultiCallable[_server_service_pb2.GetServerInfoRequest, _server_service_pb2.GetServerInfoResponse]  # type: ignore[assignment]
    """GetServerInfo returns the server's version, commit hash, and enabled features."""

class ServerServiceServicer(metaclass=_abc_1.ABCMeta):
    """ServerService provides server metadata and capability discovery.
    Always registered, no authentication required.
    """

    @_abc_1.abstractmethod
    def GetServerInfo(
        self,
        request: _server_service_pb2.GetServerInfoRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_server_service_pb2.GetServerInfoResponse, _abc.Awaitable[_server_service_pb2.GetServerInfoResponse]]:
        """GetServerInfo returns the server's version, commit hash, and enabled features."""

def add_ServerServiceServicer_to_server(servicer: ServerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
