"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetServerInfoRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetServerInfoRequest: _TypeAlias = GetServerInfoRequest  # noqa: Y015

@_typing.final
class GetServerInfoResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class FeaturesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.bool
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.bool = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    VERSION_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    FEATURES_FIELD_NUMBER: _builtins.int
    version: _builtins.str
    """Semantic version string (e.g. "1.2.3" or "dev")."""
    commit: _builtins.str
    """Git commit hash."""
    @_builtins.property
    def features(self) -> _containers.ScalarMap[_builtins.str, _builtins.bool]:
        """Enabled server features. Keys are feature names, values indicate enabled state.
        Known features: schema, config, audit, usage_tracking, jwt_auth, http_gateway.
        """

    def __init__(
        self,
        *,
        version: _builtins.str = ...,
        commit: _builtins.str = ...,
        features: _abc.Mapping[_builtins.str, _builtins.bool] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "features", b"features", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetServerInfoResponse: _TypeAlias = GetServerInfoResponse  # noqa: Y015
