# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: centralconfig/v1/server_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'centralconfig/v1/server_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%centralconfig/v1/server_service.proto\x12\x10\x63\x65ntralconfig.v1\x1a\x1cgoogle/api/annotations.proto\"\x16\n\x14GetServerInfoRequest\"\xb2\x01\n\x15GetServerInfoResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0e\n\x06\x63ommit\x18\x02 \x01(\t\x12G\n\x08\x66\x65\x61tures\x18\x03 \x03(\x0b\x32\x35.centralconfig.v1.GetServerInfoResponse.FeaturesEntry\x1a/\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x32\x8a\x01\n\rServerService\x12y\n\rGetServerInfo\x12&.centralconfig.v1.GetServerInfoRequest\x1a\'.centralconfig.v1.GetServerInfoResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/server/infob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'centralconfig.v1.server_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSERVERINFORESPONSE_FEATURESENTRY']._loaded_options = None
  _globals['_GETSERVERINFORESPONSE_FEATURESENTRY']._serialized_options = b'8\001'
  _globals['_SERVERSERVICE'].methods_by_name['GetServerInfo']._loaded_options = None
  _globals['_SERVERSERVICE'].methods_by_name['GetServerInfo']._serialized_options = b'\202\323\344\223\002\021\022\017/v1/server/info'
  _globals['_GETSERVERINFOREQUEST']._serialized_start=89
  _globals['_GETSERVERINFOREQUEST']._serialized_end=111
  _globals['_GETSERVERINFORESPONSE']._serialized_start=114
  _globals['_GETSERVERINFORESPONSE']._serialized_end=292
  _globals['_GETSERVERINFORESPONSE_FEATURESENTRY']._serialized_start=245
  _globals['_GETSERVERINFORESPONSE_FEATURESENTRY']._serialized_end=292
  _globals['_SERVERSERVICE']._serialized_start=295
  _globals['_SERVERSERVICE']._serialized_end=433
# @@protoc_insertion_point(module_scope)
