# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from centralconfig.v1 import server_service_pb2 as centralconfig_dot_v1_dot_server__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in centralconfig/v1/server_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServerServiceStub(object):
    """ServerService provides server metadata and capability discovery.
    Always registered, no authentication required.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerInfo = channel.unary_unary(
                '/centralconfig.v1.ServerService/GetServerInfo',
                request_serializer=centralconfig_dot_v1_dot_server__service__pb2.GetServerInfoRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_server__service__pb2.GetServerInfoResponse.FromString,
                _registered_method=True)


class ServerServiceServicer(object):
    """ServerService provides server metadata and capability discovery.
    Always registered, no authentication required.
    """

    def GetServerInfo(self, request, context):
        """GetServerInfo returns the server's version, commit hash, and enabled features.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=centralconfig_dot_v1_dot_server__service__pb2.GetServerInfoRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_server__service__pb2.GetServerInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'centralconfig.v1.ServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('centralconfig.v1.ServerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServerService(object):
    """ServerService provides server metadata and capability discovery.
    Always registered, no authentication required.
    """

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.ServerService/GetServerInfo',
            centralconfig_dot_v1_dot_server__service__pb2.GetServerInfoRequest.SerializeToString,
            centralconfig_dot_v1_dot_server__service__pb2.GetServerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
